# Generated by Django 2.0.1 on 2023-01-06 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='', max_length=500)),
                ('gender', models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ')], default='NAM', max_length=6)),
                ('relationship_status', models.CharField(choices=[('ĐỘC THÂN', 'Độc thân'), ('ĐÃ KẾT HÔN', 'Đã kết hôn'), ('LI HÔN', 'Li hôn')], default='ĐỘC THÂN', max_length=100)),
                ('education', models.CharField(choices=[('THPT', 'THPT'), ('CAO ĐẲNG', 'Cao đẳng'), ('ĐẠI HỌC', 'Đại học'), ('THẠC SĨ', 'Thạc sĩ'), ('TIẾN SĨ', 'Tiến sĩ')], default='ĐẠI HỌC', max_length=100)),
                ('height', models.DecimalField(decimal_places=2, default=180.34, max_digits=10)),
                ('looking_for', models.CharField(choices=[('NAM', 'Nam'), ('NỮ', 'Nữ'), ('BOTH', 'Cả hai')], default='BOTH', max_length=6)),
                ('location', models.CharField(default='', max_length=100)),
                ('birth_date', models.DateField(blank=True, default='1990-01-01', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=profiles.models.image_filename)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
