# Generated by Django 2.0.1 on 2023-01-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversations', to='chat.Conversations'),
        ),
    ]
