# Generated by Django 2.0.1 on 2023-01-11 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plans', models.CharField(choices=[('plan_one_month', 'Tháng - 200.000đ'), ('plan_three_month', '3 Tháng - 300.000đ'), ('plan_six_month', '6 Tháng - 400.000đ')], default='plan_three_month', max_length=100)),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(max_length=40)),
                ('ward', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=40)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
