# Generated by Django 2.0.1 on 2023-01-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20230102_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='county',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='town_or_city',
            new_name='ward',
        ),
        migrations.AlterField(
            model_name='order',
            name='plans',
            field=models.CharField(choices=[('plan_F5eyGdYCvZPtON', 'Tháng - 200.000đ'), ('plan_F5ey2nnZwy5v8Q', '3 Tháng - 300.000đ'), ('plan_F5eyNlWXHig7YB', '6 Thángdj - 400.000đ')], default='plan_F5ey2nnZwy5v8Q', max_length=100),
        ),
    ]
